CREATE DATABASE IF NOT EXISTS nfp;
USE nfp;

CREATE TABLE IF NOT EXISTS users (
  `user_id`   VARCHAR(256) PRIMARY KEY NOT NULL,
  `state`     VARCHAR(256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS tokens (
  id        INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `user_id`   VARCHAR(256),
  `name`     VARCHAR(20),
  meta      VARCHAR(1000),
  `address`   VARCHAR(256),
  token_type VARCHAR(256),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;